In [2]:
import numpy as np
import random

In [49]:
# data generation
# payam's formulation

# generation of the data:

E = 2
de = 1
dc = 1
d = de + dc

muc = -1
sigc = 1

mue = [1,10]
# sigenv = np.array([[1,0],[0,3]])
sige = [1,3]
f = np.array([[1,3],[0,1]])
phi = np.array([[1,-3],[0,1]])

n = 5

In [58]:
Z = np.zeros((0,d))
y = np.zeros((0,1))

# generating latent features
for i in range(len(mue)):
    ye = np.random.randint(0,2,(n,1)) * 2 -1
    Ze = np.random.randn(n, de) * sige[i] + ye * mue[i]
    Zc = np.random.randn(n, de) * sigc + ye * muc
    Znew = np.concatenate((Zc,Ze),axis=1)
    Z = np.concatenate((Z, Znew),axis=0)
    y = np.concatenate((y,ye), axis=0)

# generating data
X = Z.dot(f)

[[ -0.66000003   1.00149448]
 [  0.18323     -0.60234903]
 [ -2.04098667   0.95416604]
 [ -1.5798715   -1.47721413]
 [ -0.04280039   0.30990155]
 [ -1.32542125   8.04295327]
 [  0.91185729  14.25759351]
 [  1.35020103  -8.04929459]
 [  0.60321033 -11.3392637 ]
 [ -0.9171757   12.68635725]]
[[-0.66000003 -0.97850562]
 [ 0.18323    -0.05265902]
 [-2.04098667 -5.16879396]
 [-1.5798715  -6.21682863]
 [-0.04280039  0.18150038]
 [-1.32542125  4.06668953]
 [ 0.91185729 16.99316539]
 [ 1.35020103 -3.99869151]
 [ 0.60321033 -9.5296327 ]
 [-0.9171757   9.93483017]]


In [54]:
y

array([[-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.]])